/**
 * Opinião Real — contratos editoriais escaláveis.
 * Dados comerciais entram somente depois de verificação editorial.
 */
export const CONTENT_TYPES=Object.freeze({REVIEW:'review',GUIDE:'guide',COMPARISON:'comparison'});
export const REQUIRED_SEO=Object.freeze(['slug','metaTitle','metaDescription','primaryKeyword','h1','canonical','breadcrumbs','schemaType']);
export const EDITORIAL_RULES=Object.freeze({prohibited:['estatísticas inventadas','avaliações falsas','preços não verificados','experiências que não aconteceram','urgência artificial'],preferred:['linguagem natural','informações verificáveis','opiniões equilibradas','limitações explícitas']});
export const REVIEW_TEMPLATE=Object.freeze({type:CONTENT_TYPES.REVIEW,sections:['intro','quickSummary','explanation','comparison','individualReviews','dailyUse','howToChoose','faq','conclusion','relatedContent','affiliateDisclosure'],quickChoices:['Melhor escolha geral','Melhor custo-benefício','Melhor para iniciantes','Melhor para apartamento'],comparisonColumns:['Produto','Preço médio','Principais características','Pontos fortes','Pontos fracos','Indicação'],productFields:['name','image','summary','idealFor','pros','cons','editorialVerdict','dailyUse','affiliateUrl'],primaryCta:'Ver preço atualizado'});
export const GUIDE_TEMPLATE=Object.freeze({type:CONTENT_TYPES.GUIDE,sections:['intro','explanation','benefits','drawbacks','practicalExamples','comparison','faq','conclusion','relatedContent'],primaryCta:'Ver produtos recomendados'});
export const COMPARISON_TEMPLATE=Object.freeze({type:CONTENT_TYPES.COMPARISON,sections:['intro','directComparison','comparisonTable','advantagesAndDrawbacks','whichToChoose','faq','relatedContent','affiliateDisclosure'],comparisonColumns:['Critério','Produto A','Produto B','Veredito'],primaryCta:'Ver preço atualizado'});
export const CLUSTERS=Object.freeze({fitness:{name:'Fitness em Casa',pillar:'/melhores-bicicletas-spinning',articles:['/bicicleta-spinning-vale-a-pena','/bicicleta-spinning-para-apartamento-como-escolher','/bicicleta-spinning-emagrece','/bicicleta-spinning-profissional-ou-residencial','/melhores-esteiras-ergometricas-dobraveis','/esteira-ergometrica-vale-a-pena','/melhores-equipamentos-para-academia-em-casa','/academia-em-casa-quais-equipamentos-comprar-primeiro','/bicicleta-spinning-ou-esteira']},ferramentas:{name:'Ferramentas',pillar:'/melhores-kits-ferramentas',articles:['/kit-de-ferramentas-vale-a-pena','/melhores-parafusadeiras-sem-fio','/parafusadeira-ou-furadeira-qual-comprar','/ferramentas-essenciais-para-ter-em-casa','/melhores-marcas-de-ferramentas','/kit-ferramentas-profissional-ou-domestico','/ferramentas-sem-fio-vale-a-pena','/como-escolher-uma-parafusadeira','/melhores-ferramentas-para-pequenos-reparos']},casa:{name:'Casa e Utilidades',pillar:'/casa',articles:['/melhores-produtos-para-organizar-a-casa','/produtos-que-facilitam-a-rotina-domestica','/melhores-eletroportateis-para-casa','/produtos-uteis-que-valem-a-pena-comprar','/como-escolher-produtos-para-pequenos-espacos','/melhores-organizadores-para-casa','/produtos-inteligentes-para-casa','/itens-essenciais-para-casa-nova','/melhores-produtos-custo-beneficio-para-casa','/compras-para-casa-que-realmente-valem-a-pena']}});
export const CTA_TRACKING_CONTRACT=Object.freeze({event:'affiliate_click',requiredAttributes:['data-affiliate','data-product-id','data-product-name','data-cta-position']});
export function createArticleMetadata({type,slug,metaTitle,metaDescription,primaryKeyword,h1,canonical,breadcrumbs,schemaType='Article',cluster,relatedContent=[]}){return {type,slug,metaTitle,metaDescription,primaryKeyword,h1,canonical,breadcrumbs,schemaType,cluster,relatedContent};}
export function validateArticleMetadata(article){const missing=REQUIRED_SEO.filter(field=>!article?.[field]);if(!Array.isArray(article?.breadcrumbs)||article.breadcrumbs.length<2)missing.push('breadcrumbs');if(!Object.values(CONTENT_TYPES).includes(article?.type))missing.push('type');return {valid:missing.length===0,missing:[...new Set(missing)]};}
export function buildAffiliateAttributes({productId,productName,position}){if(!productId||!productName||!position)throw new Error('Links de afiliado exigem produto e posição de CTA identificáveis.');return {'data-affiliate':'true','data-product-id':productId,'data-product-name':productName,'data-cta-position':position};}
