import React, { useEffect, useMemo, useState } from 'react';
import { ArrowRight, BarChart3, Check, ChevronDown, ExternalLink, FileText, Menu, Search, ShieldCheck, Target, X } from 'lucide-react';
import './styles.css';
import './spinning.css';

const ML_SEARCH = 'https://lista.mercadolivre.com.br/bicicleta-spinning';

const categories = [
  { name: 'Fitness em Casa', slug: 'fitness', items: ['Bicicletas spinning', 'Esteiras', 'Equipamentos de treino'], icon: '01' },
  { name: 'Ferramentas', slug: 'ferramentas', items: ['Kits de ferramentas', 'Parafusadeiras', 'Ferramentas sem fio'], icon: '02' },
  { name: 'Casa e Utilidades', slug: 'casa', items: ['Produtos úteis', 'Organização', 'Equipamentos domésticos'], icon: '03' }
];
const guides = [
  { title: 'Melhores bicicletas spinning para casa em 2026', slug: 'melhores-bicicletas-spinning', category: 'Fitness em Casa', text: 'Compare estrutura, ajustes, resistência e espaço antes de escolher.', accent: 'fitness' },
  { title: 'Melhores esteiras dobráveis para casa', slug: 'melhores-esteiras-dobraveis', category: 'Fitness em Casa', text: 'O que analisar em uma esteira compacta para treinar em casa.', accent: 'treadmill' },
  { title: 'Melhores kits de ferramentas sem fio', slug: 'melhores-kits-ferramentas', category: 'Ferramentas', text: 'Compare versatilidade, bateria, acessórios e praticidade.', accent: 'tools' }
];

// Conteúdo comercial fica deliberadamente separado da interface. Preços, especificações e URLs de afiliado só devem ser preenchidos com dados conferidos.
const productSlots = Array.from({ length: 7 }, (_, index) => ({
  id: `produto-${index + 1}`,
  name: 'Modelo a definir',
  indication: ['Melhor escolha geral', 'Melhor custo-benefício', 'Melhor para iniciantes', 'Melhor para apartamento', 'Melhor para treinos intensos', 'Opção compacta', 'Alternativa a considerar'][index],
  summary: 'Ficha preparada para receber um produto real após conferência de especificações, avaliações e oferta disponível.',
  pros: ['Especificações verificadas', 'Pontos fortes comparados', 'Custo-benefício analisado'],
  cons: ['Pontos de atenção a conferir', 'Preço pode variar'],
  weight: 'A conferir', resources: 'A conferir', level: 'A conferir', price: 'Consultar preço atual', affiliateUrl: ML_SEARCH
}));

const faqItems = [
  ['Bicicleta spinning emagrece?', 'Pode contribuir para o gasto energético e para uma rotina de atividade física. Os resultados dependem da intensidade, frequência, alimentação e de outros fatores individuais.'],
  ['Bicicleta spinning faz muito barulho?', 'O nível de ruído varia conforme resistência, transmissão, montagem e manutenção. Em apartamento, vale comparar dimensões, estabilidade e informações consistentes sobre ruído antes da compra.'],
  ['Qual bicicleta spinning é melhor para apartamento?', 'Não existe um único modelo universalmente melhor. Para apartamento, compare principalmente dimensões, estabilidade, ruído, conforto e facilidade de movimentação.'],
  ['Quanto tempo usar bicicleta spinning por dia?', 'Isso depende do condicionamento, objetivo e orientação profissional. Para quem está começando, aumente duração e intensidade gradualmente.'],
  ['Vale a pena comprar bicicleta spinning para casa?', 'Pode valer a pena para quem pretende treinar com frequência e tem espaço adequado. Compare construção, ajustes, resistência, conforto, garantia e custo total antes de comprar.']
];

function goTo(setPage, page) { const path = page === 'home' ? '/' : `/${page}`; window.history.pushState({}, '', path); setPage(page); window.scrollTo({ top: 0, behavior: 'smooth' }); }

function Seo({ title, description, canonical, type = 'WebPage', faq = [] }) {
  useEffect(() => {
    document.title = title;
    const setMeta = (name, content) => { let el = document.head.querySelector(`meta[name="${name}"]`); if (!el) { el = document.createElement('meta'); el.name = name; document.head.appendChild(el); } el.content = content; };
    setMeta('description', description); setMeta('robots', 'index,follow');
    let link = document.head.querySelector('link[rel="canonical"]'); if (!link) { link = document.createElement('link'); link.rel = 'canonical'; document.head.appendChild(link); } link.href = canonical;
    document.getElementById('route-schema')?.remove();
    const graph = [
      { '@type': type === 'Article' ? 'Article' : 'WebPage', headline: title, name: title, description, url: canonical, isPartOf: { '@type': 'WebSite', name: 'Opinião Real', url: 'https://opiniaoreal.com/' } },
      { '@type': 'BreadcrumbList', itemListElement: [{ '@type': 'ListItem', position: 1, name: 'Início', item: 'https://opiniaoreal.com/' }, { '@type': 'ListItem', position: 2, name: 'Fitness em Casa', item: 'https://opiniaoreal.com/fitness' }, { '@type': 'ListItem', position: 3, name: 'Bicicletas spinning', item: canonical }] }
    ];
    if (faq.length) graph.push({ '@type': 'FAQPage', mainEntity: faq.map(([q, a]) => ({ '@type': 'Question', name: q, acceptedAnswer: { '@type': 'Answer', text: a } })) });
    const script = document.createElement('script'); script.id = 'route-schema'; script.type = 'application/ld+json'; script.textContent = JSON.stringify({ '@context': 'https://schema.org', '@graph': graph }); document.head.appendChild(script);
    return () => document.getElementById('route-schema')?.remove();
  }, [title, description, canonical, type, faq]);
  return null;
}

function Header({ page, setPage }) { const [open, setOpen] = useState(false); const go = p => { goTo(setPage, p); setOpen(false); }; return <header className="header"><div className="wrap nav"><button className="brand" onClick={() => go('home')} aria-label="Ir para o início"><span className="brandMark">OR</span><span>Opinião <b>Real</b></span></button><nav className={open ? 'mobileOpen' : ''}>{[['Início', 'home'], ['Fitness', 'fitness'], ['Ferramentas', 'ferramentas'], ['Casa', 'casa'], ['Comparativos', 'compare'], ['Sobre Nós', 'about']].map(([label, p]) => <button key={p} className={page === p ? 'active' : ''} onClick={() => go(p)}>{label}</button>)}</nav><button className="menu" onClick={() => setOpen(v => !v)} aria-label={open ? 'Fechar menu' : 'Abrir menu'}>{open ? <X /> : <Menu />}</button></div></header>; }

function ProductImage({ label }) { return <div className="productImage"><div className="productPlaceholder"><span>IMAGEM DO PRODUTO</span><b>{label}</b><small>Adicionar somente imagem do modelo real</small></div></div>; }

function AffiliateLink({ children, product, position, className = 'primary' }) { return <a className={className} href={product?.affiliateUrl || ML_SEARCH} target="_blank" rel="noopener noreferrer sponsored" data-affiliate="true" data-product-id={product?.id || 'spinning-search'} data-product-name={product?.name || 'Bicicletas spinning'} data-cta-position={position}>{children} <ExternalLink size={16} /></a>; }

function QuickChoice() {
  const items = [
    [0, 'Melhor escolha geral', 'Para quem quer o conjunto mais equilibrado entre construção, conforto e recursos.'],
    [1, 'Melhor custo-benefício', 'Para quem quer gastar com critério e priorizar o que realmente vai usar.'],
    [2, 'Melhor para iniciantes', 'Para quem está começando e precisa de uma opção adequada à rotina de treino.'],
    [3, 'Melhor para apartamento', 'Para quem precisa equilibrar espaço, estabilidade, conforto e ruído.']
  ];
  return <section className="quickChoice" id="ranking" aria-label="Escolha rápida"><div className="quickIntro"><span>ESCOLHA RÁPIDA</span><h2>Qual bicicleta spinning escolher?</h2><p>Use o perfil que mais se aproxima do seu objetivo para começar a comparação.</p></div><div className="quickItems">{items.map(([index, title, text]) => <a href={`#produto-${index + 1}`} key={title} className="quickCard"><b>{String(index + 1).padStart(2, '0')}</b><strong>{title}</strong><small>{text}</small><span>Ver análise <ArrowRight size={14} /></span></a>)}</div></section>;
}

function Trust() { const items = ['Comparação de características', 'Pesquisa de avaliações de compradores', 'Análise de custo-benefício', 'Pontos positivos e negativos']; return <section className="trustBlock" id="como-escolhemos"><div><p className="eyebrow">COMO ANALISAMOS</p><h2>Critérios editoriais antes do clique</h2><p>O objetivo é reduzir a dúvida antes de abrir uma oferta. Não usamos avaliações, preços, estrelas ou resultados inventados.</p></div><div className="trustList">{items.map(item => <div key={item}><Check size={17} /><span>{item}</span></div>)}</div></section>; }

function Ranking() { return <section className="rankingSection"><div className="sectionHead"><div><p className="eyebrow">RANKING</p><h2>Modelos recomendados</h2><p>Compare os pontos que realmente influenciam a decisão. Os dados comerciais devem ser conferidos antes da publicação.</p></div></div><div className="productGrid">{productSlots.slice(0, 4).map((product, index) => <article className="productCard" id={product.id} key={product.id}><ProductImage label={`Modelo ${index + 1}`} /><div className="productCardBody"><span className="rankLabel">{index === 0 ? 'RECOMENDAÇÃO GERAL' : `0${index + 1} • ${product.indication.toUpperCase()}`}</span><h3>{product.name}</h3><p>{product.summary}</p><div className="miniSpec"><span><b>Preço</b>{product.price}</span><span><b>Peso suportado</b>{product.weight}</span></div><div className="pros"><b>Pontos positivos</b>{product.pros.map(x => <span key={x}><Check size={14} />{x}</span>)}</div><div className="cons"><b>Pontos negativos</b>{product.cons.map(x => <span key={x}>− {x}</span>)}</div><AffiliateLink product={product} position={`ranking-${index + 1}`} className="cardCta">Consultar preço atualizado</AffiliateLink></div></article>)}</div></section>; }

function ComparisonTable() { return <section className="comparisonSection" id="comparativo"><div className="sectionHead"><div><p className="eyebrow">DECISÃO LADO A LADO</p><h2>Comparativo rápido</h2></div><span>Preço e disponibilidade variam conforme a oferta.</span></div><div className="tableScroll"><table><thead><tr><th>Produto</th><th>Indicação</th><th>Preço médio</th><th>Peso suportado</th><th>Nível de treino</th><th>Destaque</th><th>Oferta</th></tr></thead><tbody>{productSlots.map((p, i) => <tr key={p.id}><td><b>{i + 1}. {p.name}</b></td><td>{p.indication}</td><td>{p.price}</td><td>{p.weight}</td><td>{p.level}</td><td>{p.resources}</td><td><AffiliateLink product={p} position={`table-${i + 1}`} className="tableCta">Ver oferta</AffiliateLink></td></tr>)}</tbody></table></div></section>; }

function DetailProduct({ product, index }) { return <article className="detailProduct" id={`analise-${product.id}`}><div className="detailVisual"><ProductImage label={`Modelo ${index + 1}`} /></div><div className="detailContent"><div className="detailTitle"><span>ANÁLISE {String(index + 1).padStart(2, '0')}</span><h3>{product.name}</h3><p>{product.indication}</p></div><p><b>Resumo:</b> {product.summary}</p><p><b>Ideal para:</b> {product.indication.toLowerCase()}.</p><div className="proscons"><div><h4>Pontos positivos</h4>{product.pros.map(x => <p key={x}>+ {x}</p>)}</div><div><h4>Pontos negativos</h4>{product.cons.map(x => <p key={x}>− {x}</p>)}</div></div><p><b>Nossa avaliação:</b> a recomendação deve ser baseada nas características verificáveis do produto, no preço observado e no perfil de uso. Esta ficha não atribui nota enquanto os dados do modelo não estiverem conferidos.</p><AffiliateLink product={product} position={`detail-${index + 1}`}>Consultar preço atualizado</AffiliateLink></div></article>; }

function BuyingGuide() { const points = [['Roda de inércia', 'Ajuda a entender a sensação de pedalada e o comportamento do equipamento.'], ['Resistência', 'Compare o sistema de resistência e as possibilidades de ajuste.'], ['Conforto', 'Confira formato do banco, ajustes e posição de treino.'], ['Regulagens', 'Altura e posição do banco e guidão fazem diferença na ergonomia.'], ['Espaço', 'Confira largura, comprimento, altura e facilidade de movimentação.'], ['Peso suportado', 'Compare o limite informado pelo fabricante com seu uso previsto.']]; return <section className="buyingGuide"><p className="eyebrow">GUIA PRÁTICO</p><h2>Como escolher uma bicicleta spinning?</h2><p className="sectionIntro">A melhor compra começa pelo uso que você pretende fazer. Não escolha apenas pelo número de recursos: procure o conjunto que faz sentido para sua rotina.</p><div className="guideGrid">{points.map(([title, text], i) => <div key={title}><span>0{i + 1}</span><h3>{title}</h3><p>{text}</p></div>)}</div></section>; }

function Objections() { const items = [['Faz barulho?', 'O ruído depende da construção, transmissão, resistência, montagem e manutenção. Em apartamento, compare esse ponto antes da compra.'], ['Ocupa muito espaço?', 'Sim, o tamanho varia bastante. Confira as medidas do modelo e se existe espaço para pedalar e movimentar o equipamento.'], ['Precisa de manutenção?', 'Limpeza, aperto e cuidados indicados pelo fabricante ajudam a preservar o equipamento. Consulte sempre o manual do modelo.'], ['Serve para iniciantes?', 'Sim, desde que o modelo seja adequado ao objetivo, ergonomia e condicionamento do usuário. Comece progressivamente.'], ['Vale mais que academia?', 'Depende da rotina. Para quem treina em casa com frequência, o equipamento pode ser conveniente, mas compare custo, espaço e variedade de exercícios.']]; return <section className="objections"><p className="eyebrow">ANTES DE COMPRAR</p><h2>Veja isso antes de decidir</h2><div className="objectionGrid">{items.map(([q, a]) => <div key={q}><h3>{q}</h3><p>{a}</p></div>)}</div></section>; }

function FaqItem({ q, a }) { const [open, setOpen] = useState(false); return <div className="faqItem"><button onClick={() => setOpen(v => !v)} aria-expanded={open}><span>{q}</span>{open ? <X size={18} /> : <ChevronDown size={18} />}</button>{open && <p>{a}</p>}</div>; }
function FAQ() { return <section className="faqSection" id="faq"><p className="eyebrow">DÚVIDAS FREQUENTES</p><h2>Perguntas frequentes</h2>{faqItems.map(([q, a]) => <FaqItem key={q} q={q} a={a} />)}</section>; }

function Conclusion() { return <section className="conclusion"><p className="eyebrow">DECISÃO FINAL</p><h2>Qual bicicleta spinning escolher?</h2><p className="sectionIntro">Escolha pelo seu perfil, compare os dados e só então confira a oferta atual.</p><div className="profileGrid"><div><span>TREINOS INTENSOS</span><h3>Priorize construção, estabilidade e resistência.</h3><p>Compare estrutura, ajustes, limite de peso e garantia.</p></div><div><span>APARTAMENTO</span><h3>Priorize dimensões, estabilidade e ruído.</h3><p>Confirme o espaço disponível e as características do equipamento.</p></div><div><span>ECONOMIA</span><h3>Compare o que você realmente vai usar.</h3><p>Relacione construção, recursos, ajustes, garantia e preço atual.</p></div></div><AffiliateLink product={{ ...productSlots[0], affiliateUrl: ML_SEARCH }} position="final" className="primary finalCta">Ver preço atualizado</AffiliateLink></section>; }

function StickyNav() { return <nav className="reviewSticky" aria-label="Navegação da análise"><a href="#comparativo">Comparativo</a><a href="#ranking">Ranking</a><a href="#como-escolhemos">Como escolhemos</a><a href="#faq">Perguntas frequentes</a></nav>; }

function Review() {
  const variant = useMemo(() => new URLSearchParams(window.location.search).get('ab_variant') === 'b' ? 'b' : 'a', []);
  const title = variant === 'b' ? 'Compare as 7 Melhores Bicicletas Spinning Para Casa' : 'Melhores Bicicletas Spinning 2026';
  const primaryLabel = variant === 'b' ? 'Conferir melhor oferta' : 'Ver preço atualizado';
  useEffect(() => { window.opiniaoRealTrack?.('conversion_landing_exposure', { variant, page_type: 'spinning_review' }); }, [variant]);
  return <main className="reviewPage"><Seo title="Melhores Bicicletas Spinning para Casa em 2026 | Comparativo" description="Compare bicicletas spinning para casa, veja critérios de escolha e confira ofertas antes de comprar." canonical="https://opiniaoreal.com/melhores-bicicletas-spinning" type="Article" faq={faqItems} /><StickyNav /><div className="wrap narrow"><p className="crumb">Início <span>/</span> Fitness em Casa <span>/</span> Bicicletas spinning</p><div className="conversionHero"><div><p className="eyebrow">GUIA DE COMPRA • 2026</p><h1>{title}</h1><p className="reviewIntro">Compare modelos, descubra vantagens e escolha a bicicleta spinning ideal para seu treino.</p><div className="heroSummary"><span>🏆 <b>Melhor escolha geral</b><small>Conjunto mais equilibrado</small></span><span>💰 <b>Melhor custo-benefício</b><small>Mais equilíbrio entre entrega e preço</small></span><span>🏠 <b>Melhor para apartamento</b><small>Foco em espaço, estabilidade e ruído</small></span></div><a className="primary heroCta" href="#ranking" data-cta-position="hero">{primaryLabel} <ArrowRight size={17} /></a><div className="trust"><ShieldCheck size={19} /><span>Critérios editoriais claros. Sem avaliações, preços ou depoimentos inventados.</span></div></div><div className="heroVisual"><div className="visualLabel">ANÁLISE EM FOCO</div><div className="bikeIllustration" aria-hidden="true"><div className="bikeWheel one"/><div className="bikeWheel two"/><div className="bikeFrame f1"/><div className="bikeFrame f2"/><div className="bikeFrame f3"/><div className="bikeSeat"/><div className="bikeHandle"/></div><div className="heroNote"><Target size={18} /><span>Compare antes de comprar</span></div></div></div></div><QuickChoice /><Trust /></div><div className="contentWide"><Ranking /><ComparisonTable /></div><div className="wrap narrow"><section className="detailSection"><p className="eyebrow">ANÁLISE INDIVIDUAL</p><h2>Entenda cada recomendação</h2><p className="sectionIntro">Antes do clique, veja para quem cada categoria faz sentido, os pontos positivos e os pontos que merecem atenção.</p>{productSlots.map((p, i) => <DetailProduct key={p.id} product={p} index={i} />)}</section><BuyingGuide /><Objections /><FAQ /><Conclusion /><section className="affiliateNotice"><ShieldCheck size={20} /><p><b>Transparência:</b> alguns links desta página podem gerar comissão para o Opinião Real, sem custo adicional para você. Isso não altera os critérios editoriais.</p></section></div></main>;
}

function Benefit({ icon, title, text }) { return <div className="benefit"><div className="benefitIcon">{icon}</div><div><h3>{title}</h3><p>{text}</p></div></div>; }
function Hero() { return <section className="hero"><div className="wrap heroGrid"><div><p className="eyebrow">GUIA DE COMPRA • 2026</p><h1>Escolha melhor antes de comprar</h1><p className="lead">Análises e comparativos para transformar especificações em decisões de compra mais claras.</p><a className="primary" href="/melhores-bicicletas-spinning">Ver guia de bicicletas spinning <ArrowRight size={18} /></a></div><div className="heroVisual"><div className="visualLabel">OPINIÃO REAL</div><div className="bikeIllustration" aria-hidden="true"><div className="bikeWheel one"/><div className="bikeWheel two"/><div className="bikeFrame f1"/><div className="bikeFrame f2"/><div className="bikeFrame f3"/><div className="bikeSeat"/><div className="bikeHandle"/></div></div></div></section>; }
function Method() { const items = [['Conforto', 'Banco, ajustes e posição de treino'], ['Construção', 'Estabilidade, estrutura e acabamento'], ['Recursos', 'Resistência, painel e regulagens'], ['Custo-benefício', 'Relação entre entrega e preço praticado']]; return <section className="method"><div className="wrap methodGrid"><div><p className="eyebrow">CRITÉRIOS EDITORIAIS</p><h2>Como avaliamos</h2><p className="lead">Características técnicas, opiniões de compradores, custo-benefício e adequação ao perfil de uso.</p></div><div className="methodCards">{items.map(([title, text], i) => <div className="methodCard" key={title}><span>0{i + 1}</span><div><strong>{title}</strong><p>{text}</p></div><Check size={17} /></div>)}</div></div></section>; }
function Home({ setPage }) { return <><Seo title="Opinião Real | Análises honestas para comprar melhor" description="Análises honestas, comparativos e guias de compra para ajudar você a comprar melhor." canonical="https://opiniaoreal.com/" /><Hero /><section className="section"><div className="wrap"><div className="sectionHead"><div><p className="eyebrow">EXPLORE</p><h2>Categorias principais</h2></div><p>Conteúdo organizado para encontrar a informação certa sem perder tempo.</p></div><div className="categories">{categories.map(c => <article className="category" key={c.slug} onClick={() => goTo(setPage, c.slug)} tabIndex="0"><span className="num">{c.icon}</span><h3>{c.name}</h3><ul>{c.items.map(i => <li key={i}>{i}<ArrowRight size={15} /></li>)}</ul></article>)}</div></div></section><section className="section soft"><div className="wrap"><div className="sectionHead"><div><p className="eyebrow">INTENÇÃO DE COMPRA</p><h2>Guias de compra</h2></div></div><div className="articles">{guides.map(a => <article className="articleCard" key={a.slug} onClick={() => goTo(setPage, a.slug)} tabIndex="0"><div className={`articleImage ${a.accent}`}><div className="miniProduct" /></div><div className="articleBody"><span>{a.category}</span><h3>{a.title}</h3><p>{a.text}</p><button>Ver guia <ArrowRight size={15} /></button></div></article>)}</div></div></section><Method /><section className="section"><div className="wrap confidence"><div><p className="eyebrow">NOSSO COMPROMISSO</p><h2>Por que confiar no Opinião Real</h2><p className="lead">Informação útil, clara e honesta para apoiar decisões de compra.</p></div><div className="benefits"><Benefit icon={<FileText />} title="Análises detalhadas" text="Contexto, especificações e pontos importantes." /><Benefit icon={<BarChart3 />} title="Comparações" text="Diferenças lado a lado para facilitar a decisão." /><Benefit icon={<Search />} title="Informações claras" text="Sem promessas exageradas ou linguagem complicada." /><Benefit icon={<ShieldCheck />} title="Transparência comercial" text="Indicamos quando um link pode gerar comissão." /></div></div></section></>; }
function Category({ slug, setPage }) { const c = categories.find(x => x.slug === slug) || categories[0]; const list = guides.filter(g => g.category === c.name); return <main className="simplePage categoryPage"><Seo title={`${c.name} | Opinião Real`} description={`Guias e comparativos de ${c.name.toLowerCase()} para ajudar você a comprar melhor.`} canonical={`https://opiniaoreal.com/${slug}`} /><div className="wrap"><p className="eyebrow">CATEGORIA</p><h1>{c.name}</h1><p className="reviewIntro">Guias e comparativos para ajudar você a encontrar produtos adequados ao seu uso.</p><div className="categoryGrid">{(list.length ? list : guides).map(g => <article className="articleCard" key={g.slug} onClick={() => goTo(setPage, g.slug)}><div className={`articleImage ${g.accent}`}><div className="miniProduct" /></div><div className="articleBody"><span>{g.category}</span><h3>{g.title}</h3><p>{g.text}</p><button>Ver guia <ArrowRight size={15} /></button></div></article>)}</div></div></main>; }
function Compare() { return <main className="simplePage"><Seo title="Comparativos | Opinião Real" description="Compare produtos lado a lado antes de comprar." canonical="https://opiniaoreal.com/compare" /><div className="wrap narrow"><p className="eyebrow">FERRAMENTA DE DECISÃO</p><h1>Compare produtos lado a lado</h1><p className="reviewIntro">Use critérios objetivos para entender as diferenças antes de abrir uma oferta.</p><a className="primary" href="/melhores-bicicletas-spinning">Comparar bicicletas spinning <ArrowRight size={17} /></a></div></main>; }
function About({ contact = false }) { return <main className="simplePage"><Seo title={contact ? 'Contato | Opinião Real' : 'Sobre Nós | Opinião Real'} description="Conheça o Opinião Real e nossos critérios editoriais." canonical={`https://opiniaoreal.com/${contact ? 'contact' : 'about'}`} /><div className="wrap narrow"><p className="eyebrow">OPINIÃO REAL</p><h1>{contact ? 'Entre em contato' : 'Informação para comprar melhor'}</h1><div className="infoBlock"><h2>{contact ? 'Fale conosco' : 'Quem somos'}</h2><p>{contact ? 'Para sugerir uma correção ou falar sobre o conteúdo, utilize os canais de contato disponibilizados pelo site.' : 'O Opinião Real nasceu para ajudar consumidores a tomar decisões melhores antes de comprar produtos online, transformando especificações e comparações em conteúdo claro.'}</p><h2>Independência e transparência</h2><p>Quando usamos links de parceiros, isso é informado de forma clara. Não inventamos avaliações, preços ou depoimentos para influenciar uma decisão.</p></div></div></main>; }
function Legal({ type }) { const data = { privacy: ['Política de Privacidade', 'Esta página apresenta as diretrizes gerais de privacidade do Opinião Real.'], terms: ['Termos de Uso', 'O conteúdo do Opinião Real tem caráter informativo. Preços, disponibilidade e especificações podem mudar.'], affiliate: ['Aviso de Afiliados', 'Alguns links presentes no site podem gerar comissão caso uma compra seja realizada, sem custo adicional para o usuário.'] }[type]; return <main className="simplePage"><Seo title={`${data[0]} | Opinião Real`} description={data[1]} canonical={`https://opiniaoreal.com/${type}`} /><div className="wrap narrow"><p className="eyebrow">INFORMAÇÕES LEGAIS</p><h1>{data[0]}</h1><p className="reviewIntro">{data[1]}</p><div className="infoBlock"><h2>Transparência</h2><p>Buscamos apresentar informações claras. Se você identificar algum erro ou tiver dúvida sobre um conteúdo, entre em contato.</p></div></div></main>; }
function Footer({ setPage }) { return <footer><div className="wrap footerGrid"><div><button className="brand footerBrand" onClick={() => goTo(setPage, 'home')}><span className="brandMark">OR</span><span>Opinião <b>Real</b></span></button><p>Análises honestas para ajudar você a comprar melhor.</p></div><div><h4>Explorar</h4><button onClick={() => goTo(setPage, 'fitness')}>Fitness</button><button onClick={() => goTo(setPage, 'ferramentas')}>Ferramentas</button><button onClick={() => goTo(setPage, 'casa')}>Casa</button><button onClick={() => goTo(setPage, 'compare')}>Comparativos</button></div><div><h4>Institucional</h4><button onClick={() => goTo(setPage, 'about')}>Sobre Nós</button><button onClick={() => goTo(setPage, 'contact')}>Contato</button><button onClick={() => goTo(setPage, 'privacy')}>Privacidade</button><button onClick={() => goTo(setPage, 'terms')}>Termos</button></div><div><h4>Transparência</h4><p>Alguns links podem gerar comissão, sem custo adicional para você.</p><button onClick={() => goTo(setPage, 'affiliate')}>Aviso de Afiliados</button></div></div><div className="wrap copyright">© 2026 Opinião Real. Conteúdo editorial independente.</div></footer>; }
function App() { const initial = window.location.pathname.replace(/^\//, '') || 'home'; const [page, setPage] = useState(initial); useEffect(() => { const onPop = () => setPage(window.location.pathname.replace(/^\//, '') || 'home'); window.addEventListener('popstate', onPop); return () => window.removeEventListener('popstate', onPop); }, []); let content; if (page === 'home') content = <Home setPage={setPage} />; else if (page === 'compare') content = <Compare />; else if (['fitness', 'ferramentas', 'casa'].includes(page)) content = <Category slug={page} setPage={setPage} />; else if (page === 'melhores-bicicletas-spinning') content = <Review />; else if (guides.some(g => g.slug === page)) content = <Review />; else if (page === 'contact') content = <About contact />; else if (page === 'privacy' || page === 'terms' || page === 'affiliate') content = <Legal type={page} />; else content = <About />; return <><Header page={page} setPage={setPage} />{content}<Footer setPage={setPage} /></>; }
createRoot(document.getElementById('root')).render(<App />);
