import React, {useState} from 'react';
import {createRoot} from 'react-dom/client';
import {Search, Menu, X, ArrowRight, Check, Minus, Star, ShieldCheck, BarChart3, FileText, Mail, ChevronDown} from 'lucide-react';
import './styles.css';

const categories=[
 {name:'Fitness em Casa', items:['Bicicletas spinning','Esteiras','Equipamentos de treino'], icon:'01'},
 {name:'Ferramentas', items:['Kits de ferramentas','Parafusadeiras','Ferramentas sem fio'], icon:'02'},
 {name:'Casa e Utilidades', items:['Produtos úteis','Organização','Equipamentos domésticos'], icon:'03'}
];
const articles=[
 {category:'Fitness em Casa',title:'Melhores bicicletas spinning para casa em 2026',text:'O que observar antes de escolher uma bicicleta para treinar em casa.',accent:'fitness'},
 {category:'Fitness em Casa',title:'Melhor esteira ergométrica dobrável',text:'Um guia direto para comparar recursos, espaço e custo-benefício.',accent:'treadmill'},
 {category:'Ferramentas',title:'Melhor kit de ferramentas sem fio',text:'Como escolher um conjunto versátil para manutenção e projetos domésticos.',accent:'tools'}
];
const products=[
 ['Bicicleta Spinning A','R$ 1.200–1.800','Treino diário','Boa construção e ajuste','Pode exigir espaço extra','8,9'],
 ['Bicicleta Spinning B','R$ 900–1.300','Iniciantes','Bom custo-benefício','Menos ajustes','8,4'],
 ['Bicicleta Spinning C','R$ 1.700–2.500','Uso intenso','Mais recursos e estabilidade','Preço mais alto','9,1']
];
function Header({page,setPage}){const [open,setOpen]=useState(false);return <header className="header"><div className="wrap nav"><button className="brand" onClick={()=>setPage('home')} aria-label="Ir para o início"><span className="brandMark">OR</span><span>Opinião <b>Real</b></span></button><nav className={open?'mobileOpen':''}>{[['Início','home'],['Fitness','fitness'],['Ferramentas','tools'],['Casa','home'],['Comparativos','review'],['Sobre Nós','about']].map(([l,p])=><button key={l} className={page===p?'active':''} onClick={()=>{setPage(p);setOpen(false)}}>{l}</button>)}</nav><button className="menu" onClick={()=>setOpen(!open)} aria-label="Menu">{open?<X/>:<Menu/>}</button></div></header>}
function Hero({setPage}){return <section className="hero"><div className="wrap heroGrid"><div><p className="eyebrow">GUIA DE COMPRA • OPINIÃO REAL</p><h1>Analisamos produtos para ajudar você a <em>escolher melhor</em></h1><p className="lead">Comparativos, avaliações e guias de compra baseados em características, opiniões de consumidores e custo-benefício.</p><button className="primary" onClick={()=>setPage('review')}>Ver análises <ArrowRight size={18}/></button><div className="trust"><ShieldCheck size={19}/><span>Conteúdo independente e transparente</span></div></div><div className="heroVisual"><div className="visualLabel">ANÁLISE EM FOCO</div><div className="productShape"><div className="wheel"></div><div className="frame"></div><div className="seat"></div><div className="handle"></div></div><div className="score"><span>NOTA FINAL</span><strong>9,1</strong><small>Excelente</small></div></div></div></section>}
function Home({setPage}){return <><Hero setPage={setPage}/><section className="section"><div className="wrap"><div className="sectionHead"><div><p className="eyebrow">EXPLORE</p><h2>Categorias principais</h2></div><p>Conteúdo organizado para encontrar a informação certa sem perder tempo.</p></div><div className="categories">{categories.map(c=><article className="category" key={c.name}><span className="num">{c.icon}</span><h3>{c.name}</h3><ul>{c.items.map(i=><li key={i}><span>{i}</span><ArrowRight size={15}/></li>)}</ul></article>)}</div></div></section><section className="section soft"><div className="wrap"><div className="sectionHead"><div><p className="eyebrow">NOSSAS ESCOLHAS</p><h2>Análises em destaque</h2></div><button className="textBtn" onClick={()=>setPage('review')}>Ver todos <ArrowRight size={16}/></button></div><div className="articles">{articles.map(a=><ArticleCard key={a.title} article={a} onClick={()=>setPage('review')}/>)}</div></div></section><Method/><section className="section"><div className="wrap confidence"><div><p className="eyebrow">NOSSO COMPROMISSO</p><h2>Por que confiar no Opinião Real</h2><p className="lead">A ideia é simples: facilitar decisões de compra com informação que seja útil, clara e honesta.</p></div><div className="benefits"><Benefit icon={<FileText/>} title="Análises detalhadas" text="Contexto, especificações e pontos importantes em cada avaliação."/><Benefit icon={<BarChart3/>} title="Comparações" text="Colocamos opções lado a lado para facilitar a decisão."/><Benefit icon={<Search/>} title="Informações claras" text="Sem promessas exageradas ou linguagem complicada."/><Benefit icon={<ShieldCheck/>} title="Transparência comercial" text="Deixamos claro quando um link pode gerar comissão."/></div></div></section></>}
function ArticleCard({article,onClick}){return <article className="articleCard" onClick={onClick}><div className={'articleImage '+article.accent}><div className="miniProduct"></div></div><div className="articleBody"><span>{article.category}</span><h3>{article.title}</h3><p>{article.text}</p><button>Leia a análise <ArrowRight size={15}/></button></div></article>}
function Benefit({icon,title,text}){return <div className="benefit"><div className="benefitIcon">{icon}</div><div><h3>{title}</h3><p>{text}</p></div></div>}
function Method(){return <section className="section method"><div className="wrap methodGrid"><div><p className="eyebrow">NOSSA METODOLOGIA</p><h2>Como avaliamos</h2><p className="lead">Não existe produto perfeito para todo mundo. Por isso, olhamos para os fatores que realmente mudam a decisão.</p></div><div className="methodList">{['Avaliações de compradores','Características técnicas','Custo-benefício','Pontos positivos e negativos','Experiência de uso'].map((x,i)=><div key={x}><span>0{i+1}</span><b>{x}</b><Check size={17}/></div>)}</div></div></section>}
function Review(){return <main className="reviewPage"><div className="wrap narrow"><p className="crumb">Fitness em Casa <span>/</span> Guias de compra</p><p className="eyebrow">GUIA COMPLETO • ATUALIZADO EM 2026</p><h1>Melhores bicicletas spinning para casa em 2026: guia completo</h1><p className="reviewIntro">Escolher uma bicicleta spinning envolve mais do que comparar preços. Neste guia, reunimos os principais critérios para você entender as diferenças entre os modelos e encontrar uma opção adequada ao seu treino.</p><div className="reviewMeta"><span>Por Opinião Real</span><span>•</span><span>Leitura: 8 min</span></div></div><div className="wrap tableWrap"><div className="tableTop"><div><p className="eyebrow">COMPARATIVO</p><h2>Modelos analisados</h2></div><span className="updated">Valores são referências e podem variar.</span></div><div className="tableScroll"><table><thead><tr><th>Produto</th><th>Preço médio</th><th>Indicação</th><th>Pontos positivos</th><th>Pontos negativos</th><th>Nota</th></tr></thead><tbody>{products.map(p=><tr key={p[0]}>{p.map((v,i)=><td key={i} className={i===5?'rating':''}>{i===5&&<Star size={15}/>} {v}</td>)}</tr>)}</tbody></table></div></div><div className="wrap narrow"><div className="recommend"><div><span className="tag">NOSSA RECOMENDAÇÃO</span><h2>Um bom equilíbrio entre estrutura, conforto e custo-benefício</h2><p>A escolha final depende da sua rotina e do espaço disponível. Antes de comprar, confira as medidas, os ajustes e as condições atuais da oferta.</p><div className="proscons"><div><h3>Prós</h3><p>+ Estrutura estável</p><p>+ Ajustes para diferentes usuários</p><p>+ Boa relação entre recursos e preço</p></div><div><h3>Contras</h3><p>− Ocupa espaço considerável</p><p>− O preço pode variar bastante</p></div></div><div className="actions"><a href="#" className="primary">Ver preço atualizado <ArrowRight size={17}/></a><a href="#" className="secondary">Consultar oferta</a></div></div><div className="recommendVisual"><div className="productShape small"><div className="wheel"></div><div className="frame"></div><div className="seat"></div><div className="handle"></div></div></div></div><section className="articleText"><h2>Para quem é indicado</h2><p>Uma bicicleta spinning pode ser interessante para quem busca praticidade para treinar em casa, especialmente quando a regularidade importa mais do que ter uma grande variedade de equipamentos.</p><h2>Perguntas frequentes</h2><FAQ q="Bicicleta spinning é boa para iniciantes?" a="Sim. O mais importante é escolher um modelo com ajustes adequados e começar com uma carga compatível com seu condicionamento."/><FAQ q="O que devo observar antes de comprar?" a="Confira resistência, ajustes, peso suportado, dimensões, garantia e disponibilidade de assistência."/><FAQ q="O preço informado é fixo?" a="Não. Preços e disponibilidade mudam. Use os botões de oferta para consultar o valor atual antes da compra."/></section></div></main>}
function FAQ({q,a}){const [open,setOpen]=useState(false);return <div className="faq"><button onClick={()=>setOpen(!open)}><span>{q}</span>{open?<X size={18}/>:<ChevronDown size={18}/>}</button>{open&&<p>{a}</p>}</div>}
function About({contact=false}){return <main className="simplePage"><div className="wrap narrow"><p className="eyebrow">OPINIÃO REAL</p><h1>{contact?'Entre em contato':'Informação para comprar melhor'}</h1>{contact?<><p className="reviewIntro">Encontrou um erro, quer sugerir um produto ou falar com a equipe? Envie uma mensagem.</p><form className="contactForm" onSubmit={e=>e.preventDefault()}><label>Nome<input placeholder="Seu nome"/></label><label>E-mail<input type="email" placeholder="seu@email.com"/></label><label>Mensagem<textarea placeholder="Como podemos ajudar?"></textarea></label><button className="primary">Enviar mensagem <ArrowRight size={17}/></button></form></>:<><p className="reviewIntro">O Opinião Real nasceu para ajudar consumidores a tomar decisões melhores antes de comprar produtos online. Nosso foco é transformar especificações, opiniões e comparações em conteúdo que faça sentido para pessoas reais.</p><div className="infoBlock"><h2>Independência e transparência</h2><p>Não criamos avaliações para favorecer uma marca. Quando usamos links de parceiros, isso é informado de forma clara. A existência de uma comissão não altera o objetivo do conteúdo: ajudar você a decidir.</p><h2>Conteúdo responsável</h2><p>Preços, disponibilidade e características podem mudar. Sempre recomendamos conferir as informações no site do vendedor antes de concluir uma compra.</p></div></>}</div></main>}
function Footer({setPage}){return <footer><div className="wrap footerGrid"><div><button className="brand footerBrand" onClick={()=>setPage('home')}><span className="brandMark">OR</span><span>Opinião <b>Real</b></span></button><p>Análises honestas para ajudar você a comprar melhor.</p></div><div><h4>Explorar</h4><button onClick={()=>setPage('fitness')}>Fitness</button><button onClick={()=>setPage('tools')}>Ferramentas</button><button onClick={()=>setPage('review')}>Comparativos</button></div><div><h4>Institucional</h4><button onClick={()=>setPage('about')}>Sobre Nós</button><button onClick={()=>setPage('contact')}>Contato</button><button onClick={()=>setPage('privacy')}>Política de Privacidade</button><button onClick={()=>setPage('terms')}>Termos de Uso</button></div><div><h4>Transparência</h4><p>Participamos de programas de afiliados. Alguns links podem gerar comissão, sem custo adicional para você.</p></div></div><div className="wrap copyright">© 2026 Opinião Real. Conteúdo editorial independente.</div></footer>}
function Legal({type}){const data={privacy:['Política de Privacidade','Esta página apresenta as diretrizes gerais de privacidade do Opinião Real. Podemos coletar dados enviados voluntariamente em formulários, além de informações técnicas necessárias para funcionamento, segurança e melhoria do site.'],terms:['Termos de Uso','O conteúdo do Opinião Real tem caráter informativo. Preços, disponibilidade, especificações e condições comerciais podem mudar. O usuário deve conferir os dados diretamente com o vendedor antes de realizar uma compra.'],affiliate:['Aviso de Afiliados','O Opinião Real participa de programas de afiliados. Alguns links presentes no site podem gerar comissão caso uma compra seja realizada, sem custo adicional para o usuário. Nossa avaliação editorial não é vendida aos anunciantes.']}[type];return <main className="simplePage"><div className="wrap narrow"><p className="eyebrow">INFORMAÇÕES LEGAIS</p><h1>{data[0]}</h1><p className="reviewIntro">{data[1]}</p><div className="infoBlock"><h2>Transparência</h2><p>Buscamos apresentar informações claras e atualizadas. Se você identificar algum erro ou tiver dúvida sobre um conteúdo, entre em contato conosco.</p></div></div></main>}
function App(){const [page,setPage]=useState('home');let content=page==='home'?<Home setPage={setPage}/>:page==='review'||page==='fitness'||page==='tools'?<Review/>:page==='contact'?<About contact/>:page==='privacy'?<Legal type="privacy"/>:page==='terms'?<Legal type="terms"/>:page==='affiliate'?<Legal type="affiliate"/>:<About/>;return <><Header page={page} setPage={setPage}/>{content}<Footer setPage={setPage}/></>}

createRoot(document.getElementById('root')).render(<App/>);
