<?php get_header(); $faq=or_meta('or_faq'); $summary=array(or_meta('or_best_choice'),or_meta('or_best_value'),or_meta('or_best_alternative')); ?>
<article class="or-article"><div class="or-container"><header class="or-article-header"><?php or_breadcrumbs(); ?><p class="or-eyebrow"><?php $terms=get_the_terms(get_the_ID(),'topic'); echo $terms && !is_wp_error($terms) ? esc_html($terms[0]->name) : 'Análise e guia'; ?></p><h1><?php the_title(); ?></h1><div class="or-meta">Publicado em <?php echo esc_html(get_the_date()); ?> · Atualizado em <?php echo esc_html(get_the_modified_date()); ?> · Equipe Opinião Real</div><p class="or-article-lead"><?php echo esc_html(get_the_excerpt()); ?></p><?php if(has_post_thumbnail()): ?><div class="or-featured"><?php the_post_thumbnail('full',array('loading'=>'eager')); ?></div><?php endif; ?></header>
<div class="or-content"><?php if(array_filter($summary)): ?><section class="or-summary" aria-label="Resumo rápido"><p class="or-eyebrow">Resumo rápido</p><div class="or-summary-grid"><?php foreach(array('🏆 Melhor escolha','💰 Melhor custo-benefício','⭐ Melhor alternativa') as $i=>$label): ?><div class="or-summary-item"><strong><?php echo esc_html($label); ?></strong><span><?php echo esc_html($summary[$i] ?: 'A definir após validação editorial.'); ?></span></div><?php endforeach; ?></div></section><?php endif; ?>
<?php the_content(); ?>
<?php if($faq): $items=json_decode($faq,true); if(is_array($items)): ?><section><h2>Perguntas frequentes</h2><div class="or-faq"><?php foreach($items as $item): if(!empty($item['question']) && isset($item['answer'])): ?><details><summary><?php echo esc_html($item['question']); ?></summary><p><?php echo wp_kses_post($item['answer']); ?></p></details><?php endif; endforeach; ?></div></section><?php endif; endif; ?>
<section><h2>Conclusão</h2><p>A melhor escolha depende do seu objetivo, espaço, orçamento e das características verificáveis do produto. Consulte as informações atualizadas antes de comprar.</p></section>
<?php $affiliate=or_meta('or_affiliate_url'); $fallback=or_meta('or_pillar_url') ?: home_url('/comparativos/'); ?><aside class="or-summary or-article-cta" aria-label="Próximo passo"><p class="or-eyebrow">Próximo passo</p><h2>Veja os modelos recomendados</h2><p>Compare opções relacionadas antes de decidir.</p><a class="or-btn or-btn-primary" href="<?php echo esc_url($affiliate ?: $fallback); ?>"<?php echo $affiliate ? ' rel="sponsored noopener noreferrer" target="_blank"' : ''; ?>><?php echo $affiliate ? 'Ver preço atualizado' : 'Ver melhores recomendações'; ?></a><?php if(!$affiliate): ?><p class="or-meta">Configure o link afiliado real no campo comercial do artigo para transformar este CTA em saída comercial rastreável.</p><?php endif; ?></aside>
</div></div></article>
<?php if($faq): $items=json_decode($faq,true); if(is_array($items)&&$items): $entities=array(); foreach($items as $item){if(!empty($item['question'])&&isset($item['answer']))$entities[]=array('@type'=>'Question','name'=>wp_strip_all_tags($item['question']),'acceptedAnswer'=>array('@type'=>'Answer','text'=>wp_kses_post($item['answer'])));} if($entities) echo '<script type="application/ld+json">'.wp_json_encode(array('@context'=>'https://schema.org','@type'=>'FAQPage','mainEntity'=>$entities),JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE).'</script>'; endif; endif; ?>
<?php get_footer(); ?>
